// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz_DeAwZcJGy0OGlLl9U-fVZJ-Yv3bP9Y',
    appId: '1:1018372435825:web:89fa6265c59cca515510d0',
    messagingSenderId: '1018372435825',
    projectId: 'tml-sandbox',
    authDomain: 'tml-sandbox.firebaseapp.com',
    databaseURL: 'https://tml-sandbox-default-rtdb.firebaseio.com',
    storageBucket: 'tml-sandbox.appspot.com',
    measurementId: 'G-FQYNDR2KNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGqmYuUmMK0xnMKHxOo-FsjeRLj6DrGKg',
    appId: '1:1018372435825:android:1b9e5b3adfc14a7d5510d0',
    messagingSenderId: '1018372435825',
    projectId: 'tml-sandbox',
    databaseURL: 'https://tml-sandbox-default-rtdb.firebaseio.com',
    storageBucket: 'tml-sandbox.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY39WfcV91imXiru2NAFwKdzqUaUlIY58',
    appId: '1:1018372435825:ios:06903ac2ce7fb5b55510d0',
    messagingSenderId: '1018372435825',
    projectId: 'tml-sandbox',
    databaseURL: 'https://tml-sandbox-default-rtdb.firebaseio.com',
    storageBucket: 'tml-sandbox.appspot.com',
    androidClientId: '1018372435825-9v5417v3356o3u30pqe1o7dr9o7j2ofp.apps.googleusercontent.com',
    iosClientId: '1018372435825-nco1t4evo9cqff0hs9tlj70s1v3mdecm.apps.googleusercontent.com',
    iosBundleId: 'com.tml.flutterfirelab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY39WfcV91imXiru2NAFwKdzqUaUlIY58',
    appId: '1:1018372435825:ios:06903ac2ce7fb5b55510d0',
    messagingSenderId: '1018372435825',
    projectId: 'tml-sandbox',
    databaseURL: 'https://tml-sandbox-default-rtdb.firebaseio.com',
    storageBucket: 'tml-sandbox.appspot.com',
    androidClientId: '1018372435825-9v5417v3356o3u30pqe1o7dr9o7j2ofp.apps.googleusercontent.com',
    iosClientId: '1018372435825-nco1t4evo9cqff0hs9tlj70s1v3mdecm.apps.googleusercontent.com',
    iosBundleId: 'com.tml.flutterfirelab',
  );
}
